/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtigosRouteImport } from './routes/artigos'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CursosRouteImport } from './routes/cursos'
import { Route as DireitosEServicosRouteImport } from './routes/direitos-e-servicos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtigosRoute = ArtigosRouteImport.update({
  id: '/artigos',
  path: '/artigos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosRoute = CursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => rootRouteImport,
} as any)
const DireitosEServicosRoute = DireitosEServicosRouteImport.update({
  id: '/direitos-e-servicos',
  path: '/direitos-e-servicos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artigos': typeof ArtigosRoute
  '/contato': typeof ContatoRoute
  '/cursos': typeof CursosRoute
  '/direitos-e-servicos': typeof DireitosEServicosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artigos': typeof ArtigosRoute
  '/contato': typeof ContatoRoute
  '/cursos': typeof CursosRoute
  '/direitos-e-servicos': typeof DireitosEServicosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artigos': typeof ArtigosRoute
  '/contato': typeof ContatoRoute
  '/cursos': typeof CursosRoute
  '/direitos-e-servicos': typeof DireitosEServicosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/artigos' | '/contato' | '/cursos' | '/direitos-e-servicos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/artigos' | '/contato' | '/cursos' | '/direitos-e-servicos'
  id:
    | '__root__'
    | '/'
    | '/artigos'
    | '/contato'
    | '/cursos'
    | '/direitos-e-servicos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtigosRoute: typeof ArtigosRoute
  ContatoRoute: typeof ContatoRoute
  CursosRoute: typeof CursosRoute
  DireitosEServicosRoute: typeof DireitosEServicosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artigos': {
      id: '/artigos'
      path: '/artigos'
      fullPath: '/artigos'
      preLoaderRoute: typeof ArtigosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos': {
      id: '/cursos'
      path: '/cursos'
      fullPath: '/cursos'
      preLoaderRoute: typeof CursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/direitos-e-servicos': {
      id: '/direitos-e-servicos'
      path: '/direitos-e-servicos'
      fullPath: '/direitos-e-servicos'
      preLoaderRoute: typeof DireitosEServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtigosRoute: ArtigosRoute,
  ContatoRoute: ContatoRoute,
  CursosRoute: CursosRoute,
  DireitosEServicosRoute: DireitosEServicosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
